# Generated by Django 5.0 on 2023-12-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("practiceApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                ("about", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[("IT", "IT"), ("Non IT", "Non IT")], max_length=100
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
