# Generated by Django 5.0 on 2023-12-26 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("practiceApp", "0002_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email_id", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=100)),
                ("mobile_no", models.CharField(max_length=10)),
                ("about", models.TextField()),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("manager", "manager"),
                            ("software devloper", "SD"),
                            ("Project Leader", "PL"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "Company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="practiceApp.company",
                    ),
                ),
            ],
        ),
    ]
